language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    include:
        - php: 5.6
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_VERSION='2.8.3'
        - php: 7.0
          env: SYMFONY_VERSION='2.8.3'
        - php: 5.6
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_VERSION='3.0.3'
        - php: 7.0
          env: SYMFONY_VERSION='3.0.3'

install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - composer update --prefer-source $COMPOSER_FLAGS

script: phpunit -v


